# Generated by Django 5.2.13 on 2026-04-25 17:37

from django.db import migrations, models


def seed_sort_order(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    for index, product in enumerate(Product.objects.order_by('-created_at', 'id'), start=1):
        Product.objects.filter(pk=product.pk).update(sort_order=index)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariant_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['sort_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.RunPython(seed_sort_order, migrations.RunPython.noop),
    ]
